name: Scrapy deploy

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build file
        run: |
          echo $GITHUB_REPOSITORY_OWNER 
          echo "python"